### PR TITLE
Optionally Hide Reports

### PR DESCRIPTION
**Pull request by mdellabitta**
Added config/application.rb parameter for hiding the Reports link.

### CODE REVIEW

**Comment by AudreyAltman** [comment]
:+1:  In some of our other rails apps, we use the `rails-config` gem, which allows us to manage settings-type variables in yml files.  I don't think it's necessary now, but we can keep it in mind in the future if we start accumulating a lot of settings-type variables.  It also might simplify deployments (@markbreedlove would know better than I).

**Comment by mdellabitta** [comment]
At first I actually made this an environment variable. I'm not really sure what's better.

**Review by markbreedlove — CHANGES_REQUESTED** [review]
It will be easiest to configure during deployments if we can update the variable in our `dpla.yml` configuration file. Here's and example of how it's done already, with the property `api_auth.allow_all_keys` in that file, and then the method `Config.allow_all_api_keys?`:

In config.rb:

https://github.com/dpla/platform-cqa/blob/c38b588b7860cdc4fd90f0bcc48a2036fc40ce6b/v1/lib/v1/config.rb#L22-L25

and then in the application controller:

https://github.com/dpla/platform-cqa/blob/c38b588b7860cdc4fd90f0bcc48a2036fc40ce6b/v1/app/controllers/v1/application_controller.rb#L31-L34

**Comment by mdellabitta** [comment]
Okies, will revise.

**Review by markbreedlove — APPROVED** [review]

**Pull request merged**
